version: '3.5'

services:
  rinhadebackend-aot:
    &api
    hostname: api01
    image: ${DOCKER_REGISTRY-}rinhadebackendaot
    build:
      context: .
      dockerfile: RinhaDeBackEnd-AOT/Dockerfile
    environment:
      - DB_HOSTNAME=Host=db;Database=rinha;Username=admin;Password=123;No Reset On Close=true;Max Auto Prepare=10;Auto Prepare Min Usages=1;Pooling=true;Maximum Pool Size=30
    deploy:
      resources:
        limits:
          cpus: "0.32"
          memory: "160MB"

  rinhadebackend-aot02:
    <<: *api 
    hostname: api02
    depends_on:
       - rinhadebackend-aot
       - db
  nginx:
    image: nginx:latest
    volumes:
     - ./nginx-conf/default.conf:/etc/nginx/nginx.conf
    depends_on:
      - rinhadebackend-aot
      - rinhadebackend-aot02
    ports:
      - "9999:9999" 
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "30MB"

  db:
    image: postgres:latest
    hostname: db
    command: 'postgres -c max_connections=371'
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./pg-conf/script.sql:/docker-entrypoint-initdb.d/script.sql
    deploy:
      resources:
        limits:
          cpus: "0.7"
          memory: "200MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1
