<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-RinhaDeBackEnd_AOT.Worker-c2d9601e-5bd9-4040-aa8b-ad66c01e831a</UserSecretsId>
    <RootNamespace>RinhaDeBackEnd_AOT.Worker</RootNamespace>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.7" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.0" />
    <PackageReference Include="Polly" Version="8.6.2" />
    <PackageReference Include="Polly.Extensions" Version="8.6.2" />
    <PackageReference Include="StackExchange.Redis" Version="2.8.41" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RinhaDeBackEnd-AOT.Domain\RinhaDeBackEnd-AOT.Domain.csproj" />
    <ProjectReference Include="..\RinhaDeBackEnd-AOT.Infrastructure\RinhaDeBackEnd-AOT.Infrastructure.csproj" />
  </ItemGroup>
	
  <ItemGroup>
    <Content Update="appsettings.json" CopyToPublishDirectory="Never" />
    <Content Update="appsettings.Development.json" CopyToPublishDirectory="Never" />
  </ItemGroup>
</Project>
