// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace RinhaDeBackEndAOT.Models
{
    public partial class AppDbContextModel
    {
        private AppDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("e14bf92e-1b1b-4994-a4c2-6ff873c17d44"), entityTypeCount: 2)
        {
        }

        partial void Initialize()
        {
            var gatewayStatsResult = GatewayStatsResultEntityType.Create(this);
            var transaction = TransactionEntityType.Create(this);

            GatewayStatsResultEntityType.CreateAnnotations(gatewayStatsResult);
            TransactionEntityType.CreateAnnotations(transaction);

            AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            AddAnnotation("ProductVersion", "9.0.7");
            AddAnnotation("Relational:MaxIdentifierLength", 63);
        }
    }
}
