// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using RinhaDeBackEnd_AOT.Infra.Contexts;
using RinhaDeBackEndAOT.Models;


#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(AppDbContext), typeof(AppDbContextModel))]
